---
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/rbaumgardner93/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    version: main
  tags:
  - install
  - dotfiles
# - name: Install from Brewfile
#  shell: brew bundle install --file=~/dotfiles/brew/Brewfile
#  tags:
#  - install
#  - dotfiles
- name: Install Stow
  shell: brew install stow
  tags:
  - install
  - dotfiles
- name: Stow dotfiles
  shell: "cd {{ lookup('env', 'HOME') }}/dotfiles && stow brew git kitty nvim tmux"
  tags:
  - install
  - dotfiles
