---
- name: Install node and set version to latest LTS
  shell: ". {{ lookup('env', 'HOME') }}/.nvm/nvm.sh && nvm install --lts && nvm use --lts"
  args:
    executable: /bin/zsh
  tags:
  - install
  - node
